/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';
import Paper from '../components/utils/Paper';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Paper className="m-0 mb-4 rounded-none">
          <div className="flex justify-center  text-4xl">
            Hello
            <span className="text-green-900 text-4xl px-2"> Dev</span>, I'm
            styled using tailwindcss
          </div>
        </Paper>
      </main>
    </div>
  );
}
