/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex justify-center text-gray-700 text-4xl">
          Hello
          <span className="text-green-900 text-4xl px-2 "> Dev</span>, I'm
          styled using tailwindcss
        </div>
      </main>
    </div>
  );
}
